### PR TITLE
fix: improve attribute error messages

### LINKED ISSUE #741: Improve error message for invalid attributes
At the moment, someone using the MySQL2 (best guess) instrumentation is encountering an error message like:
```
E, [2021-05-04T09:18:39.581149 #31471] ERROR -- : OpenTelemetry error: invalid attribute value type NilClass
```
This doesn't help narrow down the source of the error. We should at least include the span name in the message. This comes from https://github.com/open-telemetry/opentelemetry-ruby/blob/e7da54d8aa5ac89009020c7a7a28afe2e1315c6a/sdk/lib/opentelemetry/sdk/internal.rb#L47-L59

This is called from a few places in the SDK `Span` class:
https://github.com/open-telemetry/opentelemetry-ruby/blob/e7da54d8aa5ac89009020c7a7a28afe2e1315c6a/sdk/lib/opentelemetry/sdk/trace/span.rb#L304-L308

https://github.com/open-telemetry/opentelemetry-ruby/blob/e7da54d8aa5ac89009020c7a7a28afe2e1315c6a/sdk/lib/opentelemetry/sdk/trace/span.rb#L332

https://github.com/open-telemetry/opentelemetry-ruby/blob/e7da54d8aa5ac89009020c7a7a28afe2e1315c6a/sdk/lib/opentelemetry/sdk/trace/span.rb#L349

### PR DESCRIPTION
**Pull request by fbogsany**
Fixes #741

### CODE REVIEW

File: sdk/lib/opentelemetry/sdk/internal.rb [hunk 1]
```diff
@@ -44,13 +44,13 @@ def valid_value?(value)
...
-      def valid_attributes?(attrs)
+      def valid_attributes?(owner, kind, attrs)
         attrs.nil? || attrs.all? do |k, v|
           if !valid_key?(k)
-            OpenTelemetry.handle_error(message: "invalid attribute key type #{k.class}")
+            OpenTelemetry.handle_error(message: "invalid #{kind} attribute key type #{k.class} on span '#{owner}'")
             false
           elsif !valid_value?(v)
-            OpenTelemetry.handle_error(message: "invalid attribute value type #{v.class}")
+            OpenTelemetry.handle_error(message: "invalid #{kind} attribute value type #{v.class} on span '#{owner}'")
```
Comment (robertlaurin) [inline sdk/lib/opentelemetry/sdk/internal.rb:53]: I think it would be valuable to identify which key has a nil value associated with it.

Comment (fbogsany) [reply sdk/lib/opentelemetry/sdk/internal.rb:53]: 🤦 of course

Comment (fbogsany) [reply sdk/lib/opentelemetry/sdk/internal.rb]: done

**Review by robertlaurin — APPROVED** [review]
