### PR TITLE
fix: Adds User-Agent header in OTLP exporter

### LINKED ISSUE #1385: OTLP exporters should emit standard user agent string
As per the following change in the specification (1.14 releasing Oct 4):

> OpenTelemetry protocol exporters SHOULD emit a User-Agent header to at a minimum identify the exporter, the language of its implementation, and the version of the exporter. For example, the Python OTLP exporter version 1.2.3 would report the following:
> ```OTel OTLP Exporter Python/1.2.3```

See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#user-agent

### PR DESCRIPTION
**Pull request by Coolomina**
Fixes #1385.

In the context of tests, I think it would be more readable to have the raw string in the expectation (Ej: `"OTel OTLP Exporter Ruby/0.24.1"`), rather than have it interpolated.

[Unlike rspec](https://relishapp.com/rspec/rspec-mocks/v/2-11/docs/stubbing-constants/stub-defined-constant#stub-nested-constant), I'm reading that `minitest` does not provide out of the box mechanisms for stubbing constants and other external libraries may be required, so even though I don't personally like it, I'm leaving it interpolated for the sake of not adding more dependencies in the codebase.

Also, I bumped the patch because #1385 is flagged as `bug`, even though it feels more like a `feature` to me.

### CODE REVIEW

**Review by ahayworth — APPROVED** [review]
Looks good to me! Thank you! 😄

File: exporter/otlp/lib/opentelemetry/exporter/otlp/version.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ module OpenTelemetry
   module Exporter
     module OTLP
       ## Current OpenTelemetry OTLP exporter version
-      VERSION = '0.24.0'
+      VERSION = '0.24.1'
```
Comment (plantfansam) [inline exporter/otlp/lib/opentelemetry/exporter/otlp/version.rb:11]: I think our release machinery will handle bumping this

**Review by plantfansam — CHANGES_REQUESTED** [review]
Seems good to me! IDK about reaching into the exporter for instance variables during tests, but that pattern is already established. Don't need to bump the gem version in this PR, tho.

File: exporter/otlp/lib/opentelemetry/exporter/otlp/version.rb (hunk 1 above)
Comment (Coolomina) [reply exporter/otlp/lib/opentelemetry/exporter/otlp/version.rb]: Done!

**Comment by Coolomina** [comment]
If necessary, I can squash those two commits together so we don't have that last crappy commit 😂

**Review by robertlaurin — APPROVED** [review]

**Comment by robertlaurin** [comment]
@plantfansam any remaining blockers from you? I can't merge until your changes requested gets cleared.

File: exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb [hunk 2]
```diff
@@ -70,6 +70,7 @@ def initialize(endpoint: OpenTelemetry::Common::Utilities.config_opt('OTEL_EXPOR
                      else
                        raise ArgumentError, ERROR_MESSAGE_INVALID_HEADERS
                      end
+          @headers['User-Agent'] = "OTel OTLP Exporter Ruby/#{OpenTelemetry::Exporter::OTLP::VERSION}"
```
Comment (fbogsany) [inline exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb:73]: This is the first time we're mutating the `headers` Hash that's passed in. In general, we assume the caller maintains ownership and doesn't want us stomping on their hash. Arguably, we should have `dup`ed the hash in the `when Hash` branch above, in case the caller subsequently mutated it. I think we should do that anyway, then we own the hash and this line is 👍 .

Comment (robbkidd) [reply exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb:73]:
```suggestion
          @headers['User-Agent'] = "OTel-OTLP-Exporter-Ruby/#{OpenTelemetry::Exporter::OTLP::VERSION}"
```

Product identifiers in a User-Agent come in [the format of a token](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.6) and therefore should not include spaces, despite [the current spaced-string example provided in the OTel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/ff19b9e8212fae4296f63d307591d781d4613304/specification/protocol/exporter.md#user-agent). Spaces in this value are going to mess up a looooot of parsers.

**Review by robbkidd — CHANGES_REQUESTED** [review]
In addition to the request to dup headers before mutation, I'll add that the user-agent string we ship must _not_ include spaces in the "product identifier." That was totally what the OTel spec example provided, but the spec's example is ... not wholly correct.

Update: I've opened [a PR](https://github.com/open-telemetry/opentelemetry-specification/pull/3052) to the OTel spec to propose a no-spaces fix to the example there, too.

**Comment by robbkidd** [comment]
Ooof. I'm sorry I've slept on this PR for so long.

@Coolomina, if you're still in on bring this PR home, I'd like to help! I've got an idea for how to implement @fbogsany's recommendation that we `dup` the incoming headers Hash to protect the exporter's config from later mutation.

I'd also like to propose

1. _Augmenting_ whatever User-Agent may appear in the incoming headers by concatenating ours to any value present.

2. Including more Ruby runtime information to the user-agent, something like:

```ruby
"OTel-OTLP-Exporter-Ruby//#{OpenTelemetry::Exporter::OTLP::VERSION} Ruby/#{RUBY_VERSION} (#{RUBY_PLATFORM})"
# -> OTel-OTLP-Exporter-Ruby/0.24.0 Ruby/3.2.1 (arm64-darwin22)
```

Or even including the engine name and version:

```ruby
"OTel-OTLP-Exporter-Ruby/#{OpenTelemetry::Exporter::OTLP::VERSION} Ruby/#{RUBY_VERSION} (#{RUBY_PLATFORM}; #{RUBY_ENGINE}/#{RUBY_VERSION})"
# -> OTel-OTLP-Exporter-Ruby/0.24.0 Ruby/3.2.1 (arm64-darwin22; ruby/3.2.1)
# … or … 
# -> OTel-OTLP-Exporter-Ruby/0.24.0 Ruby/3.2.0 (opal; opal/3.2.0)
# (I couldn't get JRuby running quickly to make this example.
```

**Comment by robbkidd** [comment]
@Coolomina, are you still interested and available to continue work on this PR? If not, I'd like to take on the work to address PR comments and get it merged.

**Comment by robbkidd** [comment]
As a followup to the removal of the version bump, I pushed a small removal of the changelog entry for that version bump, too.

**Comment by robbkidd** [comment]
Another followup this week to remove spaces from the user-agent header, add more runtime info, and dupe the incoming headers from config to protect against future mutation.

**Review by robbkidd — APPROVED** [review]

**Comment by robbkidd** [comment]
@plantfansam, would you be up for a re-review of this PR to address your requested changes (dupe headers to protect from outside mutation)?

**Comment by robbkidd** [comment]
Bitten by new cops!

**Review by ericmustin — APPROVED** [review]
lgtm assuming cops r addressed

**Review by plantfansam — APPROVED** [review]
👍

**Review by fbogsany — APPROVED** [review]
