### PR TITLE
fix: rescue OpenSSL errors during export

### LINKED ISSUE #883: Rescue OpenSSL::SSL::SSLError
According to the spec:

> The SDK MUST NOT throw unhandled exceptions for errors in their own operations. For example, an exporter should not throw an exception when it cannot reach the endpoint to which it sends telemetry data.

Unfortunately, we encountered an exception with v0.16.0 and Ruby 3.0.1 which resulted in an HTTP 500 for our service:

```text
OpenSSL::SSL::SSLError
SSL_read: decryption failed or bad record mac
/usr/local/lib/ruby/3.0.0/openssl/buffering.rb:205:in `sysread_nonblock'
/usr/local/lib/ruby/3.0.0/openssl/buffering.rb:205:in `read_nonblock'
/usr/local/lib/ruby/3.0.0/net/protocol.rb:212:in `rbuf_fill'
/usr/local/lib/ruby/3.0.0/net/protocol.rb:193:in `readuntil'
/usr/local/lib/ruby/3.0.0/net/protocol.rb:203:in `readline'
/usr/local/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
/usr/local/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
/usr/local/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
/usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
/usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
/usr/local/lib/ruby/3.0.0/net/http.rb:1521:in `request'
/usr/local/bundle/gems/opentelemetry-instrumentation-net_http-0.16.0/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb:35:in `block in request'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace/tracer.rb:29:in `block in in_span'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace.rb:82:in `block in with_span'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/context.rb:62:in `with_value'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace.rb:82:in `with_span'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace/tracer.rb:29:in `in_span'
/usr/local/bundle/gems/opentelemetry-instrumentation-net_http-0.16.0/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb:22:in `request'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:161:in `block (2 levels) in send_bytes'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:208:in `measure_request_duration'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:161:in `block in send_bytes'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:136:in `block in around_request'
/usr/local/bundle/gems/opentelemetry-common-0.16.0/lib/opentelemetry/common/utilities.rb:60:in `block in untraced'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace.rb:82:in `block in with_span'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/context.rb:62:in `with_value'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace.rb:82:in `with_span'
/usr/local/bundle/gems/opentelemetry-common-0.16.0/lib/opentelemetry/common/utilities.rb:60:in `untraced'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:136:in `around_request'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:143:in `send_bytes'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:76:in `export'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186:in `block in export_batch'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186:in `synchronize'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186:in `export_batch'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:113:in `force_flush'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:81:in `block in force_flush'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:78:in `synchronize'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:78:in `force_flush'
```

Chatting with @arielvalentin, it seems like we might need to add OpenSSL errors to a list here: https://github.com/open-telemetry/opentelemetry-ruby/blob/980f0e454c59e822de439635ee513e2bcdf820b8/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L199-L211

### PR DESCRIPTION
**Pull request by robbkidd**
Closes #883

### CODE REVIEW

File: exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb [hunk 1]
```diff
@@ -182,6 +182,15 @@
       _(result).must_equal(FAILURE)
     end
 
+    it 'returns FAILURE when encryption to receiver endpoint fails' do
+      stub_request(:post, 'https://localhost:4317/v1/traces').to_raise(OpenSSL::SSL::SSLError.new('enigma wedged'))
+      span_data = create_span_data
+      tight_retry_interval = ->(_) { 0.01 }
```
Comment (robbkidd) [inline exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb:188]: This is dirty and I do feel bad about it. I tried using [the prior art](https://github.com/open-telemetry/opentelemetry-ruby/blob/980f0e454c59e822de439635ee513e2bcdf820b8/exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb#L166-L172) for stubbing `backoff?`, but it had some weird interactions that prevented `send_bytes()` from ever reaching the last retry attempt for the `rescue` blocks to get past `backoff?` and return a `FAILURE`. I suppose another alternative to this would be to stub `backoff?` to return false to short-circuit retries.

Comment (robbkidd) [reply exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb:188]: Without doing something about `backoff?`, the default number of retries (5), the default overall timeout (10 seconds), and `backoff?'s exponentially-growing random sleeping fails attempts to verify that `FAILURE` is returned by any of the exception handling. Their overall timeout time is exceeded before the 5 retries complete.

Comment (fbogsany) [reply exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb:188]: Did you include the previous line `@retry_count = 0` when stubbing `backoff?` (and the `ensure` block as well, though that’s probably overkill)?

I think stubbing `backoff?` to return `false` is the right approach here. You shouldn’t need to care about retries for this test.

Comment (arielvalentin) [reply exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb:188]: Self shunting is perfectly reasonable in my opinion. 

Other options maybe to stub the `RETRY` constant or allow for the retries to be configurable and default to the constant value. 

I personally lean towards making the exporter configurable because it encapsulates the functionality in the exporter but do not object to using this testing pattern.

File: exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb [hunk 2]
```diff
@@ -199,6 +199,9 @@ def send_bytes(bytes, timeout:) # rubocop:disable Metrics/AbcSize, Metrics/Cyclo
           rescue Net::OpenTimeout, Net::ReadTimeout
             retry if backoff?(retry_count: retry_count += 1, reason: 'timeout')
             return FAILURE
+          rescue OpenSSL::SSL::SSLError
+            retry if backoff?(retry_count: retry_count += 1, reason: 'openssl_error')
```
Comment (arielvalentin) [inline exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb:203]: This is out of the scope of this PR but I would be interested in knowing more details of the exception if I ran into this in production. Anyone have an appetite for me to open an issue about adding more exception details to the log?

File: exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb (hunk 1 above)
Comment (robbkidd) [reply exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb:188]: > Did you include the previous line @retry_count = 0 when stubbing backoff?

Pretty sure I did, but those buffers are lost to me now.

poof

> I think stubbing `backoff?` to return `false` is the right approach here. You shouldn’t need to care about retries for this test.

I agree that's better. Or at least less bad. Though, I'll note that with the default exporter configuration, `send_bytes()` will rarely if ever hit the `return FAILURE`s in the rescue blocks. `send_bytes()` will [`return TIMEOUT`](https://github.com/open-telemetry/opentelemetry-ruby/blob/980f0e454c59e822de439635ee513e2bcdf820b8/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L167) as the 10 seconds is exceeded in the first 3-4 attempts. We'll be relying on deltas in the `otel.otlp_exporter.failure` metrics emitted to track down gremlins within the timeouts.

File: exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb (hunk 2 above)
Comment (robbkidd) [reply exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb:203]: I had wondered about that, too, with [the logging done for encoding errors](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb#L192-L209).

File: exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb [hunk 3]
```diff
@@ -182,6 +182,14 @@
       _(result).must_equal(FAILURE)
     end
 
+    it 'returns FAILURE when encryption to receiver endpoint fails' do
+      stub_request(:post, 'https://localhost:4317/v1/traces').to_raise(OpenSSL::SSL::SSLError.new('enigma wedged'))
+      span_data = create_span_data
+      exporter.stub(:backoff?, ->(**_) { false }) do
```
Comment (robbkidd) [inline exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb:188]: Updated to use arcane stabby lambda to short-circuit backoff and retries. I'm open to making this more verbose and maybe a local variable to give names to what's going on here to reduce the eldritch Ruby..

**Review by fbogsany — APPROVED** [review]

File: exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb (hunk 3 above)
Comment (fbogsany) [reply exporter/otlp/test/opentelemetry/exporter/otlp/exporter_test.rb:188]: I think this is fine.
