### PR TITLE
fix: improve configuration error reporting

### LINKED ISSUE #664: Obscure configuration error
My first experience with this gem was:

```
E, [2021-03-18T04:14:42.145080 #24298] ERROR -- : OpenTelemetry error: unexpected configuration error - OpenTelemetry::SDK::ConfigurationError
```

There was an error in my configuration, which was roughly copied from an example in an issue within this repository:

```
OpenTelemetry::SDK.configure do |config|
  config.service_name = "..."
  config.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
      exporter: OpenTelemetry::Exporter::OTLP::Exporter.new(
        endpoint: "ingest.lightstep.com:43/api/v2/otel/trace",
        insecure: false.
        headers: { "lightstep-access-token" => ENV.fetch("LIGHTSTEP_TOKEN") }
      )
    )
  )
end 
```

It was revealed when I wrapped it to output more information about the exception:

```
OpenTelemetry::SDK.configure do |config|
  begin
    config.service_name = "..."
    config.add_span_processor(
      OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
        exporter: OpenTelemetry::Exporter::OTLP::Exporter.new(
          endpoint: "ingest.lightstep.com:43/api/v2/otel/trace",
          insecure: false.
          headers: { "lightstep-access-token" => ENV.fetch("LIGHTSTEP_TOKEN") }
        
      )
    )
  rescue
    puts "#{$!.class.name}: #{$!}", *$!.backtrace 
    raise
  end
end 
```

(it was `unknown keyword: :insecure`)

Perhaps whatever is logging this error should provide more context?

### PR DESCRIPTION
**Pull request by fbogsany**
Fixes #664

### CODE REVIEW

File: sdk/test/opentelemetry/sdk_test.rb [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+        received_message = message
+      end
+
+      OpenTelemetry::SDK.configure do |config|
+        # This fails due to an invalid argument.
+        config.add_span_processor(OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(nil, invalid_option: 'foo'))
+      end
+
+      _(received_exception).must_be_instance_of OpenTelemetry::SDK::ConfigurationError
+      _(received_message).must_equal('unexpected configuration error due to unknown keyword: :invalid_option')
```
Comment (robertlaurin) [inline sdk/test/opentelemetry/sdk_test.rb:31]: It appears the formatting changed in `2.7`, maybe we can use a looser `match` assertion on the string?
```
-"unexpected configuration error due to unknown keyword: :invalid_option"
+"unexpected configuration error due to unknown keyword: invalid_option"
```

**Review by robertlaurin — APPROVED** [review]
🎉
