### PR TITLE
fix!: refactor Baggage to remove Noop*

### LINKED ISSUE #789: Consider exposing Baggage `Manager` as functions
As `BaggageManager` is not required in other SIGs API (as there won't be specialized implementations, as opposed to traces/metrics), consider removing this class and expose the functionality directly, e.g.

```ruby
module Baggage
  def build(context:Context) # etc
```

This is also how these functions are exposed in Python, btw. Not a strong feeling though.

### PR DESCRIPTION
**Pull request by fbogsany**
Fixes #789 and #790

### CODE REVIEW

File: api/lib/opentelemetry/baggage.rb [hunk 1]
```diff
@@ -7,13 +7,103 @@
...
+    extend self
+
+    BAGGAGE_KEY = OpenTelemetry::Baggage::Propagation::ContextKeys.baggage_key
+    EMPTY_BAGGAGE = {}.freeze
+    private_constant(:BAGGAGE_KEY, :EMPTY_BAGGAGE)
+
+    # Used to chain modifications to baggage. The result is a
+    # context with an updated baggage. If only a single
+    # modification is being made to baggage, use the other
+    # methods on +Manager+, if multiple modifications are being made, use
```
Comment (ahayworth) [inline api/lib/opentelemetry/baggage.rb:24]:
```suggestion
    # methods on +Baggage+, if multiple modifications are being made, use
```

**Review by ahayworth — APPROVED** [review]
LGTM, one suspected typo but otherwise 👍
